// Generated by dts-bundle-generator v5.8.0

export declare type Json = undefined | null | boolean | number | string | Json[] | {
	[prop: string]: Json;
};
export declare type FabricCallbackData<T extends Json = null> = {
	code: "fabric_catched_error" | string;
	data: T;
};
export declare type FabricDebugOptions = {
	enableDebug: boolean;
};
export declare type FabricDebugCallbackData = FabricCallbackData<{
	enabled: boolean;
}>;
export declare const fabricUtils: {
	setDebugStatus: (options: import("./type.debug").FabricDebugOptions) => import("./type.debug").FabricDebugCallbackData;
};
export declare const fabricX: () => string;

export {};
